name: Update Timestamps

on: [push]

jobs:
  update-timestamps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run timestamp update script
        run: |
          # Check if this is the first commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            # Get the list of markdown files in the first commit
            changed_files=$(git ls-files '*.md')
          else
            # Get the list of modified or created markdown files in the current commit
            changed_files=$(git diff --name-only --diff-filter=ACM HEAD~1 HEAD -- '*.md')
          fi

          # Check if there are any markdown files changed
          if [ -z "$changed_files" ]; then
            echo "No markdown files were modified or created in this commit."
            exit 0
          fi

          # Get the current date and time
          current_date=$(date "+%Y-%m-%d %H:%M:%S")

          # Process each changed markdown file
          for file in $changed_files; do
            echo "Processing file: $file"

            # Check if 'createdAt' does not exist, then add it
            if ! grep -q "^createdAt:" "$file"; then
              sed -i "0,/^---$/!b;//a\\createdAt: $current_date" "$file"
            fi

            # If 'modifiedAt' exists, update it; otherwise, add it
            if grep -q "^modifiedAt:" "$file"; then
              sed -i "s/^modifiedAt:.*/modifiedAt: $current_date/" "$file"
            else
              sed -i "0,/^createdAt:.*/!b;//a\\modifiedAt: $current_date" "$file"
            fi
          done

          # Set Git configuration
          git config --global user.email "groen.gelderland.community@gmail.com"
          git config --global user.name "TedGroenGelderland"
          
          # Add and commit the changes
          git add .
          git commit -m "Update timestamps"
          git push
